### ISSUE TITLE
Problem with {% load staticfiles %} when using 1.5.0, installed through pypi or pip; wheel incorrect

### ISSUE THREAD

**Issue by ganzevoort** [labd/wagtail-2fa#139]
Hi, I'm running into a problem with `{% load staticfiles %}` when using the current version (1.5.0, installed through pypi). This was fixed a long time ago (#42, feb 2020).

Inspecting the [downloadfiles](https://pypi.org/project/wagtail-2fa/#files), it seems the .tar file is correct, but the .whl file is not.

**Comment by nickmoreton** [comment]
I have also seen this today.

**Comment by ganzevoort** [comment]
My workaround is:
````
pip install --no-binary wagtail-2fa -r requirements.txt

**Comment by shredding** [comment]
I overwrote the `opt_form.html` template.

**Comment by michael-yin** [comment]
I also meet this problem.

The quick fix is to install the package from Github directly

```
pip install https://github.com/labd/wagtail-2fa/archive/1.5.0.tar.gz
```

**Comment by rodrigo-c** [comment]
I'd suggest editing the title of this issue to be more informative. I have this problem and took a long time to find this issue.

"Problem with {% load staticfiles %} when using 1.5.0, installed through pypi or pip."

**Comment by William-Blackie** [comment]
Those with poetry issues, this can be solved with;

**Comment by tomkins** [comment]
Looks like it's fixed with [version 1.6.0](https://github.com/labd/wagtail-2fa/releases/tag/1.6.0).

**Comment by ganzevoort** [comment]
Thanks

**Comment by diegowith** [comment]
> I overwrote the `opt_form.html` template.

how do you do that?
