### ISSUE TITLE
First login (2FA setup) doesn't work if WAGTAIL_2FA_REQUIRED

### ISSUE THREAD

**Issue by ganzevoort** [labd/wagtail-2fa#178]
The 2fa setup form needs /admin/jsi18n/ but that's refused if 2fa authentication hasn't been completed yet.
Adding `wagtailadmin_javascript_catalog` to `wagtail_2fa.middleware.VerifyUserMiddleware._allowed_url_names` solves that.

**Comment by ganzevoort** [comment]
Pull request: https://github.com/labd/wagtail-2fa/pull/179

**Comment by ababic** [comment]
This one caught me out on a new client build recently. We have also had a few incident reports from other sites. I definitely know what it's like maintaining open-source projects alongside the rest of life, but if there is a bit of time to look at this one, that would be greatly appreciated.

Thanks @ganzevoort for submitting the fix :)

**Comment by atfranc2** [comment]
Wanted to leave this comment for anyone reading this issue looking for a temporary workaround.

On the 2FA setup page where you can use a device to scan the QR code, select inspect to open dev-tools, and go to the network tab. There is a network entry called "qr-code". Follow the link to the QR code, it will open up a QR code in a new tab. Use that to set up 2FA and obtain you token on setup.

**Comment by davisnando** [comment]
Merged the pull request so I will close this issue
