### ISSUE TITLE
Package installation issue with Wagtail version 4.0.1

### ISSUE THREAD

**Issue by Karelkami** [labd/wagtail-2fa#188]
When I tried to install the package in a fresh install I got an error message related to django.contrib.auth.views.SuccessURLAllowedHostsMixin. In the latest version of Django this has been replaced by RedirectURLMixin. So I modified the views file of the package to make it work.

On line 5.
I replaced the old code with: 
`from django.contrib.auth.views import RedirectURLMixin`

At line 23.

I replaced the old code with :

`class LoginView(RedirectURLMixin, FormView):`

So ! And it works very well.

**Comment by deeprave** [comment]
Yep, confirmed here. I encountered the same issue here with Wagtail 4.1.

**Comment by rajks24** [comment]
Hi, Even I faced the same issue for `wagtail==4.1`  and the above work around resolved it.
Snippet of the error which I got 
```
File “proj/env/lib/python3.9/site-packages/wagtail_2fa/wagtail_hooks.py", line 9, in <module>
    from wagtail_2fa import views
  File “proj/env/lib/python3.9/site-packages/wagtail_2fa/views.py", line 5, in <module>
    from django.contrib.auth.views import SuccessURLAllowedHostsMixin
ImportError: cannot import name 'SuccessURLAllowedHostsMixin' from 'django.contrib.auth.views' (proj/env/lib/python3.9/site-packages/django/contrib/auth/views.py)
```

**Comment by gmisiolek** [comment]
As I can see pull request with this fix has been pulled into this repository couple days ago. When will be new release on pypi?

**Comment by robmoorman** [comment]
@davisnando can you release this to pypi please :)

**Comment by davisnando** [comment]
@robmoorman Released to pypi so closing issue
