### ISSUE TITLE
WAGTAIL_2FA_REQUIRED = False being ignored

### ISSUE THREAD

**Issue by victoriachan** [labd/wagtail-2fa#22]
Hi,

I want to disable 2fa on local builds and staging sites. So I added `WAGTAIL_2FA_REQUIRED = False` to my settings in dev.py. However I am still being prompted for 2fa. This is the same even when I remove the `WAGTAIL_2FA_REQUIRED = True` in base.py.

Does this only disable the setting of 2fa for new accounts but will continue to require it for users accounts that already have 2fa enabled?

Thanks.

**Comment by mikedingjan** [comment]
Hi @victoriachan,

Thanks for your report! 

You're right, when the user has a verified device, the code will keep asking for your MFA token as you can see here: https://github.com/labd/wagtail-2fa/blob/master/src/wagtail_2fa/middleware.py#L34 I think we should update the code so it will be disabled when te setting is set to ``False`` however for now you can maybe continue with removing your device in django admin?

**Comment by victoriachan** [comment]
Thank you for confirming, @mikedingjan!

**Comment by narun4sk** [comment]
What's is ETA for this to be sorted? I can push the PR, if this is what was blocking you?

It's quite an important setting so it's annoying that it is partly broken... :disappointed:
