### ISSUE TITLE
Can not work with `django-otp` 0.7.0

### ISSUE THREAD

**Issue by michael-yin** [labd/wagtail-2fa#24]
`django-otp` now released 0.7.0, it starts to using the latest middleware syntax.

So the old `super().process_request(request)` can not work because the method does not exist in _OTPMiddleware any more.

I suggest to add notes to README and release a new version to work with django-otp 0.7.0

You can check code here https://github.com/django-otp/django-otp/blob/master/src/django_otp/middleware.py

**Comment by MichielBijland** [comment]
This should already be solved but we are going to pin to 0.7.4 + in #32
