### ISSUE TITLE
Do not throw ImproperlyConfigured error when custom Verify middleware is used

### ISSUE THREAD

**Issue by robmoorman** [labd/wagtail-2fa#27]
In order to use additional rules for verification (e.g. specify which user groups need 2fa), this line breaks custom middleware core.

Maybe better option to move this to the docs as an important rule that middleware is required, rather than at runtime when he app is loaded.

https://github.com/labd/wagtail-2fa/blob/76c3cf3fb30de9b88d14571e3a1f8d4be807ad1a/src/wagtail_2fa/apps.py#L19-L22

**Comment by nnist** [comment]
This was fixed in pull request #31. It's now possible to use custom verify middleware. The exception is no longer raised, instead it's noted in the docs that the middleware has to be used.

**Comment by robmoorman** [comment]
Great @nnist !

**Comment by editkid** [comment]
Fantastic, thank you.
