### ISSUE TITLE
Reverse error on form template with fresh installation

### ISSUE THREAD

**Issue by lucasmoeskops** [labd/wagtail-2fa#29]
The view /admin/devices/new gives a Reverse error on loading:
Reverse for 'wagtail_2fa_device_list' with no arguments not found. 1 pattern(s) tried: ['admin/2fa/devices/(?P<user_id>\\d+)$']

It seems this commit has introduced this:
https://github.com/labd/wagtail-2fa/commit/0f1af73c0ffadbe597405d535ff4fcd5812f1e30#diff-5dc5c9626c083d8cadc2fd43c8aac804

An argument was added to wagtail_2fa_device_list, but not added to the url templatetag in /templates/wagtail_2fa/device_form.html.

This pull request was already made I see but not merged, and will probably fix the issue: https://github.com/labd/wagtail-2fa/pull/28/files.

**Comment by nnist** [comment]
Thanks for reporting this! It is indeed fixed by #28, which has just been merged.
