### ISSUE TITLE
2fa does not work after update to v1.3.3

### ISSUE THREAD

**Issue by btx** [labd/wagtail-2fa#35]
I've updated from v1.1.0 (django-otp pinned to v0.6.0) to v1.3.3 and 2fa stopped working.

I'm able to add 2fa device but on the next sign-in there's no OTP prompt and I get '403 Forbidden' when I go to 'MANAGE YOUR 2FA DEVICES' in my settings.

**Comment by MichielBijland** [comment]
Hi btx,

I'm unable to replicate this bug.

Could you try if you get same error using the sandbox environment by using the command below and username and password from [readme.rst](https://github.com/labd/wagtail-2fa/blob/master/README.rst)

`make sandbox`

kind regards,
Michiel

**Comment by btx** [comment]
Hello Michiel,

thanks, sandbox works. I'll try to debug my project's installation/configuration in few days and I'll get back here if I find something worth sharing.

**Comment by btx** [comment]
I'm able to replicate it in the sandbox with `WAGTAIL_2FA_REQUIRED = False`.

**Comment by nnist** [comment]
Thanks for reporting this. I just managed to replicate this too, this also happens if the new `VerifyUserPermissionsMiddleware` is used, but the user is not in a group which has 2FA enabled.
I'm working on a fix now.
