### ISSUE TITLE
Current password being marked invalid when trying to add 2FA device

### ISSUE THREAD

**Issue by delaine-eb** [labd/wagtail-2fa#38]
We updated to version 1.3.0 (and tried 1.3.4) so that admins could manage 2FA devices for other users. When attempting to create a new 2FA device, I realized I was getting an invalid password error even though I copied the password I used a few seconds before to successfully log into wagtail.

*Steps to Reproduce*

1. Deploy version 1.3.0 or 1.3.4 (haven't checked the version between but I assume those versions have this same issue)
2. Add a new device and use the password you use to log into wagtail. See that there is an invalid password error

**Comment by MichielBijland** [comment]
@delaine-eb please remove the screenshot you are leaking information about your username in qr code.

Could you try to replicate this issue using the sandbox environment, as i'm having no trouble adding multiple devices to sandbox and live environment.

**Comment by delaine-eb** [comment]
> @delaine-eb please remove the screenshot you are leaking information about your username in qr code.
> 
> Could you try to replicate this issue using the sandbox environment, as i'm having no trouble adding multiple devices to sandbox and live environment.

How would I utilize the sandbox environment?

**Comment by MichielBijland** [comment]
You have to clone this repo and follow these instructions:
https://wagtail-2fa.readthedocs.io/en/stable/#sandbox

**Comment by delaine-eb** [comment]
OK, I can try it in sandbox. I tried it in the live environment, if I'm understanding what you mean by that correctly. I installed version 1.3.0 and then tried version 1.3.4 and got that error with both versions, as did one of my co-workers.

**Comment by delaine-eb** [comment]
@MichielBijland I did some more investigation and we are using an LDAP integration. We're not using the `django.contrib.auth.backends.ModelBackend`, we're using the `django_auth_ldap.backend.LDAPBackend`. I'm suspect that the the new password check isn't compatible with the fact that we're using LDAP credentials. Could we configure this library to allow for that additional password check or not?

**Comment by MichielBijland** [comment]
@delaine-eb This is correct we are using user.check_password function we should use https://github.com/django/django/blob/master/django/contrib/auth/__init__.py#L61

This way it won't depend on user model but on authentication backends.

**Comment by MichielBijland** [comment]
Released in 1.4.0
