### ISSUE TITLE
NoReverseMatch for URLs with required parameters

### ISSUE THREAD

**Issue by PeterDekkers** [labd/wagtail-2fa#51]
Hello!

We've been using an [extended version](https://github.com/labd/wagtail-2fa/issues/51#issuecomment-606365231) of `VerifyUserMiddleware` in order to provide some additional URL names for which we never want to surface a 2FA challenge. This works fine _except_ for URLs with parameters, where `NoReverseMatch` gets thrown here:
https://github.com/labd/wagtail-2fa/blob/cf29e9254675fa59e67202a663b1f658bc7a4643/src/wagtail_2fa/middleware.py#L90-L93

Now, I'm wondering why this code doesn't use `django.urls.resolve` to compare the request's URL _name_ to the list of allowed URL names. This would make it work with all Django URLs I think.

So instead of doing this:
https://github.com/labd/wagtail-2fa/blob/cf29e9254675fa59e67202a663b1f658bc7a4643/src/wagtail_2fa/middleware.py#L72-L74

You could do something like this:
```python
current_url = resolve(request.path_info).url_name

# Don't require verification for specified paths
if current_url in self._allowed_url_names:
    return False
```
I'll set up a PR soon in case it's handy. Thanks!

**Comment by editkid** [comment]
For context, this is how we extend `VerifyUserMiddleware` in our application:
```python
from wagtail_2fa.middleware import VerifyUserMiddleware

from app.urls import RECEIPT_DOWNLOAD_URL_NAME
from api_graphql.constants import (
    API_PUBLIC_URL_NAME,
    API_PUBLIC_GRAPHIQL_URL_NAME,
    API_SSR_URL_NAME,
    API_SSR_GRAPHIQL_URL_NAME,
)


class CustomVerifyUserMiddleware(VerifyUserMiddleware):

    # Special URLs excluded from 2FA requirements
    _custom_allowed_url_names = [
        RECEIPT_DOWNLOAD_URL_NAME,
        API_PUBLIC_URL_NAME,
        API_PUBLIC_GRAPHIQL_URL_NAME,
        API_SSR_URL_NAME,
        API_SSR_GRAPHIQL_URL_NAME,
    ]

    _allowed_url_names = (
        VerifyUserMiddleware._allowed_url_names + _custom_allowed_url_names
    )
```
