### ISSUE TITLE
Add 'application name' to 2FA codes

### ISSUE THREAD

**Issue by mitchellslager** [labd/wagtail-2fa#7]
In apps like Google Authenticator you can't distinguish the 2FA codes, because it does not show any application names.

**Comment by mikedebock** [comment]
Hi Mitchell, you can configure the application name with this setting: `OTP_TOTP_ISSUER`.

**Comment by mikedingjan** [comment]
Would be nice if we make a wagtail-2fa setting for this, that sets the ``OTP_TOTP_ISSUER`` under the hood, or at least document this somewhere.

**Comment by mikedingjan** [comment]
And maby default to `WAGTAIL_SITE_NAME`
